# Generated by Django 5.2.5 on 2026-09-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(choices=[('Consulta', 'Consulta General'), ('Seguimiento', 'Seguimiento'), ('Terapia', 'Sesión de Terapia'), ('Suero', 'Suero'), ('Otro', 'Otro'), ('Psicologo', 'Psicologo'), ('Dra. Diana', 'Dra. Diana'), ('Silla Pelvica', 'Silla Pelvica'), ('Terapia con CO2', 'Terapia con CO2'), ('Dentista', 'Dentista'), ('Consulta Psicologica', 'Consulta Psicologica'), ('Microscopia', 'Microscopia')], default='Consulta', max_length=50, verbose_name='Motivo de la Cita'),
        ),
    ]
