# Generated by Django 5.2.5 on 2026-07-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinicamusculoesqueletico',
            name='no_historia_clinica',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Historia Clínica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Deporte_que_practica',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Estado_Civil',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Separado/a', 'Separado/a'), ('Unión_libre', 'Unión libre')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Nacionalidad',
            field=models.CharField(blank=True, choices=[('Mexicana', 'Mexicana'), ('Extranjero', 'Extranjero')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Ocupacion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Pasatiempo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Religion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Residencia_Anterior',
            field=models.CharField(blank=True, help_text='En caso de aplicar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='menarquia',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='no_de_parejas',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinicamusculoesqueletico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_musculoesqueleticos', to='Pacientes.paciente'),
        ),
    ]
