# Generated by Django 4.2.23 on 2025-09-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
