# Generated by Django 4.2.23 on 2025-12-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="Deporte_que_practica",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Estado_Civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Soltero/a", "Soltero/a"),
                    ("Casado/a", "Casado"),
                    ("Divorciado/a", "Divorciado/a"),
                    ("Viudo/a", "Viudo/a"),
                    ("Separado/a", "Separado/a"),
                    ("Unión_libre", "Unión libre"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[("Mexicana", "Mexicana"), ("Extranjero", "Extranjero")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Ocupacion",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Pasatiempo",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Religion",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="Residencia_Anterior",
            field=models.CharField(
                blank=True, help_text="En caso de aplicar", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="edad",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=""),
        ),
    ]
