# Generated by Django 4.2.23 on 2025-12-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Pacientes",
            "0002_paciente_deporte_que_practica_paciente_estado_civil_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiaclinica",
            name="menarquia",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historiaclinica",
            name="no_de_parejas",
            field=models.CharField(blank=True, null=True),
        ),
    ]
