# Generated by Django 5.2.5 on 2025-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(choices=[('Consulta', 'Consulta General'), ('Seguimiento', 'Seguimiento'), ('Terapia', 'Sesión de Terapia'), ('Suero', 'Suero'), ('Otro', 'Otro')], default='Consulta', max_length=50, verbose_name='Motivo de la Cita'),
        ),
    ]
