# Generated by Django 5.2.5 on 2026-08-27 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioInsumos', '0001_initial'),
        ('Pacientes', '0002_historiaclinicamusculoesqueletico_no_historia_clinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consulta')),
                ('descripcion_procedimiento', models.TextField(verbose_name='Procedimiento realizado y evolución')),
                ('medicamentos_recetados', models.TextField(blank=True, null=True, verbose_name='Medicamentos recetados')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_consultas', to='Pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventarioInsumos.insumo')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='Pacientes.registroconsulta')),
            ],
        ),
    ]
