# Generated by Django 4.2.23 on 2026-01-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Pacientes", "0003_alter_historiaclinica_menarquia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiaclinicamusculoesqueletico",
            name="no_historia_clinica",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Número de Historia Clínica",
            ),
        ),
        migrations.AlterField(
            model_name="historiaclinicamusculoesqueletico",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiales_musculoesqueleticos",
                to="Pacientes.paciente",
            ),
        ),
    ]
