# Generated by Django 5.2.5 on 2026-09-18 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorteDeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('doctora', 'Doctora'), ('farmacia', 'Farmacia')], max_length=10, verbose_name='Rol del Corte')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('fondo_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fondo Inicial en Caja')),
                ('monto_final_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final Contado')),
                ('monto_final_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final Tarjeta')),
                ('monto_final_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final Transferencia')),
                ('diferencia_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia Tarjeta')),
                ('diferencia_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia Transferencia')),
                ('total_ventas_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total de Ventas (Calculado)')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia')),
                ('is_open', models.BooleanField(blank=True, null=True, verbose_name='¿Está abierto?')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Medicamento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('cantidad_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Disponible')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('Transferencia', 'Transferencia Bancaria')], default='Efectivo', max_length=20, verbose_name='Método de Pago')),
                ('monto_pagado_por_cliente', models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto dinero entregó el cliente', max_digits=10)),
                ('cambio_devuelto', models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto se le devolvió', max_digits=10)),
            ],
        ),
    ]
