# Generated by Django 5.2.5 on 2026-08-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio_devuelto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto se le devolvió', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('Transferencia', 'Transferencia Bancaria')], default='Efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado_por_cliente',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto dinero entregó el cliente', max_digits=10),
        ),
    ]
