<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-16 00:14
=======
# Generated by Django 5.2.5 on 2025-08-31 19:40
>>>>>>> eb0a250e227e6cfb1e03d0168ee1d6bcbf15e81b

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventario.venta'),
        ),
    ]
