# Generated by Django 4.2.23 on 2025-10-11 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="farmaceuta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="Inventario.tag", verbose_name="Etiquetas"
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="medicamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_venta",
                to="Inventario.medicamento",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Inventario.venta",
            ),
        ),
        migrations.AddField(
            model_name="cortedecaja",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
