# Generated by Django 5.2.5 on 2026-09-19 00:38

import django.db.models.deletion
from django.db import migrations, models


def asignar_doctor_existente(apps, schema_editor):
    Doctor = apps.get_model('Pacientes', 'Doctor')
    FarmaciaProfile = apps.get_model('Pacientes', 'FarmaciaProfile')
    Medicamento = apps.get_model('Inventario', 'Medicamento')
    Venta = apps.get_model('Inventario', 'Venta')

    primer_doctor = Doctor.objects.order_by('user_id').first()
    if primer_doctor:
        Medicamento.objects.filter(doctor__isnull=True).update(doctor=primer_doctor)

    for venta in Venta.objects.filter(doctor__isnull=True):
        doctor = None
        if venta.farmaceuta_id:
            doctor = Doctor.objects.filter(user_id=venta.farmaceuta_id).first()
            if not doctor:
                farmacia = FarmaciaProfile.objects.filter(user_id=venta.farmaceuta_id).first()
                if farmacia:
                    doctor = Doctor.objects.filter(pk=farmacia.doctor_id).first()
        venta.doctor = doctor or primer_doctor
        venta.save(update_fields=['doctor'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_initial'),
        ('Pacientes', '0002_alcance_por_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='Pacientes.doctor', verbose_name='Doctor dueño'),
        ),
        migrations.AddField(
            model_name='venta',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='Pacientes.doctor', verbose_name='Doctor dueño'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Medicamento'),
        ),
        migrations.RunPython(asignar_doctor_existente, noop),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('doctor', 'nombre'), name='uniq_medicamento_doctor_nombre'),
        ),
    ]
