# Generated by Django 5.2.5 on 2026-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_venta_cambio_devuelto_venta_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortedecaja',
            name='diferencia_tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia Tarjeta'),
        ),
        migrations.AddField(
            model_name='cortedecaja',
            name='diferencia_transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia Transferencia'),
        ),
        migrations.AddField(
            model_name='cortedecaja',
            name='monto_final_tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final Tarjeta'),
        ),
        migrations.AddField(
            model_name='cortedecaja',
            name='monto_final_transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final Transferencia'),
        ),
    ]
