# Generated by Django 4.2.23 on 2025-10-11 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TagInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Insumo"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fabricante"
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "cantidad_disponible",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad Disponible",
                    ),
                ),
                (
                    "precio_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio de Compra",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        to="InventarioInsumos.taginsumo",
                        verbose_name="Etiquetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo",
                "verbose_name_plural": "Insumos",
                "ordering": ["nombre"],
            },
        ),
    ]
