# Generated by Django 5.2.5 on 2026-09-19 00:38

import django.db.models.deletion
from django.db import migrations, models


def asignar_doctor_insumos(apps, schema_editor):
    Doctor = apps.get_model('Pacientes', 'Doctor')
    Insumo = apps.get_model('InventarioInsumos', 'Insumo')
    primer_doctor = Doctor.objects.order_by('user_id').first()
    if primer_doctor:
        Insumo.objects.filter(doctor__isnull=True).update(doctor=primer_doctor)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioInsumos', '0001_initial'),
        ('Pacientes', '0002_alcance_por_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='Pacientes.doctor', verbose_name='Doctor dueño'),
        ),
        migrations.RunPython(asignar_doctor_insumos, noop),
    ]
